### ISSUE TITLE
Problems running on Raspberry PI 2

### ISSUE THREAD

**Issue by S1MB10T3** [vavrek/openassistant#12]
I'm getting this error when running `/run.sh -c -H20 -m0 -M mind/boot`

```
pi@raspberrypi:~/openassistant$ ./run.sh -c -H20 -m0 -M mind/boot
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/util/connection.py", line 60, in create_connectin
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x756f7c90>: Failed to en

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.speech.cs.cmu.edu', port=80): Max retries exc)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/openassistant/run.py", line 167, in <module>
    l.update_language()
  File "/home/pi/openassistant/modules/language/__init__.py", line 78, in update_language
    r = requests.post(url, files=files, data=values)
  File "/home/pi/.local/lib/python3.5/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.speech.cs.cmu.edu', port=80): Max retries )
```

**Comment by joshuashort** [comment]
Is that Pi connected to the Internet? The current codebase downloads stuff every time it starts. Another possibility is the link it's hitting is dead, but it doesn't seem like a 404..

**Comment by joshuashort** [comment]
https://github.com/vavrek/openassistant/blob/6a51f51c0599d4843310334adffe3a4a6f3404e8/modules/language/__init__.py#L65

**Comment by S1MB10T3** [comment]
Yeah, It was just the internet connection. I retried it on different network and it works now.

**Comment by joshuashort** [comment]
@Rantahu if you're comfortable with editing the source, you can bypass the network requirement.. ideally the request should be optional (I never liked that being a requirement), and the system should be okay with trying to locate that file (i.e. as long as the output file exists, it should be fine with loading it).

**Comment by S1MB10T3** [comment]
I guess a  try and except method would work. I'll work on it sometime soon...

**Comment by joshuashort** [comment]
That and not being a mandatory call..
